### ISSUE TITLE
Subscriptions Endpoint in Electron

### ISSUE THREAD

**Issue by simPod** [prismagraphql/graphql-playground#715]
#### This issue pertains to the following package(s):

- [ ] GraphQL Playground - Electron App

#### What OS and OS version are you experiencing the issue(s) on?

Latest macos

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?
1.5.9

Installed using `brew cask install graphql-playground`

Is there a way to set subscriptions endpoint? I'm not running js server and my subscriptions server has different url and port. Thanks!

**Comment by lekterable** [comment]
@simPod currently you can do this only by creating a `.graphqlconfig.yml` file according to https://github.com/prisma/graphql-config

Here is an example:
```
extensions:
  endpoints:
    default:
      url: 'http://localhost:4000/graphql'
      subscription: 
        url: 'ws://localhost:5000/subscription'
```
