### ISSUE TITLE
Save / Load workspace

### ISSUE THREAD

**Issue by nicolas-besnard** [prismagraphql/graphql-playground#727]
I'm using `graphql-playground` for several projects, and I'd like to know if there's any plan to "persist" workspaces by given them a name, and saving specific queries under that workspace?

**Comment by einaralex** [comment]
You can specify your projects in .graphqlconfig, see more at https://github.com/prismagraphql/graphql-config

**Comment by BenHizak** [comment]
Is there any way of saving tabs in the project folder? 
(tab name, query)

**Comment by gihrig** [comment]
Saving tab content used to just happen, even over whole computer restarts. Recently the playground no longer saves tab content and even looses all content periodically in the same session.

Prisma v1.18.0
node 10.12.0
Mac OS 10.11.6

**Comment by Jayphen** [comment]
I have the same problem with all state resetting whenever I load the app on MacOS (10.14)

**Comment by joelgetaction** [comment]
I have the same problem.  Also, save file does not work or do anything and queries are lost across app starts ... This makes it difficult to use GraphQLPlayground because I have to retype a bunch of queries each time ...

**Comment by gihrig** [comment]
These problems don't exist in the playground app. I have abandoned the web-based playground.

**Comment by joelgetaction** [comment]
Thanks @gihrig but I *was* using the playground app, installed from homebrew, the latest version.  Trying to save, nothing happens, no save menu pops up, nothing.  :-(

Could you walk me through how you save things?  Are you creating a blank config file and launching from there or are you typing in queries and then saving somehow?  This would help me a lot ... :-)

**Comment by gihrig** [comment]
@joelgetaction 

> I was using the playground app, installed from homebrew

Wow, that's strange. I hope my success ins't just "beginner's luck".

Since the web version lost all of my queries, all I did was:

1. Install playground app, using homebrew
2. I don't recall, but I probably had to enter my GraphQL end point URL
3. Manually enter some queries
4. Press CMD-S to save

Next time I opened Playground app I was presented with a splash screen where I can select a recent workspace, create a new workspace or select another URL Endpoint.

I have two existing workspace choices, both contain the same tabs?. My tabs are all as I have left them. History works as expected, shows all my recent queries and starred queries filter works too.

I have a basic `graphqlconfig.yml` in my project root. This is pretty much as created by `prisma init`, or was it `graphql init`? It's been a while...

Except for the `${env...}` vars, it's pretty standard.
```yaml
projects:
  app:
    schemaPath: src/schema.graphql
    extensions:
      endpoints:
        default: ${env:APP_HOST}
  database:
    schemaPath: src/generated/prisma.graphql
    extensions:
      prisma: database/prisma.yml
      endpoints:
        dev:
          url: ${env:PRISMA_ENDPOINT}
          headers:
            Authorization: Bearer ${env:GQL_AUTH_TOKEN}
      prepare-bundle: src/generated/database.graphql
```
Also, I have many files in `~/Library/Application Support/GraphQL Playground` and `.../graphql-ide`.

![image](https://user-images.githubusercontent.com/1481063/47948182-1708d080-dee9-11e8-8ffb-9376fbb4a33f.png)

I hope this helps, let me know how it goes.
